start-at-login = true
after-startup-command = [
  'exec-and-forget borders',
  # 'exec-and-forget defaults write -g NSAutomaticWindowAnimationsEnabled -bool false',
]
key-mapping.preset = 'qwerty'

# for sketchybar
# exec-on-workspace-change = [
# 	'/bin/bash',
# 	'-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE',
# ]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 10

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

cmd-r = 'reload-config'

cmd-enter = 'exec-and-forget open -n /Applications/Ghostty.app/'
cmd-b = 'exec-and-forget open -n /Applications/Brave\ Browser.app/'
cmd-shift-b = 'exec-and-forget open -n /Applications/Firefox.app/'

cmd-slash = 'layout tiles horizontal vertical'
cmd-shift-slash = 'layout accordion horizontal vertical'

cmd-w = 'close'
# cmd-tab = 'focus-back-and-forth'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'
cmd-semicolon = 'macos-native-minimize'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'
cmd-alt-h = 'join-with left'
cmd-alt-j = 'join-with down'
cmd-alt-k = 'join-with up'
cmd-alt-l = 'join-with right'


# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# cmd-leftSquareBracket = 'join-with left'
# cmd-rightSquareBracket = 'join-with right'

cmd-m = 'fullscreen'
# cmd-f = 'macos-native-fullscreen'

# cmd-s = 'layout v_accordion' # 'layout stacking' in i3
# cmd-w = 'layout h_accordion' # 'layout tabbed' in i3

cmd-comma = 'workspace prev'
# cmd-shift-comma = ''
cmd-period = 'workspace next'
# cmd-shift-period = ''

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

# cmd-rightSquareBracket = 'move-workspace-to-monitor prev'
# cmd-leftSquareBracket = 'move-workspace-to-monitor next'

cmd-e = 'balance-sizes'
cmd-shift-r = 'mode resize'
# cmd-shift-semicolon = 'mode service'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
cmd-shift-r = 'mode main'
esc = 'mode main'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# [mode.service.binding]
# 	esc = ['reload-config', 'mode main']
# 	r = ['flatten-workspace-tree', 'mode main'] # reset layout
#     # s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
# 	cmd-f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# 	backspace = ['close-all-windows-but-current', 'mode main']
#
# 	alt-shift-h = ['join-with left', 'mode main']
# 	alt-shift-j = ['join-with down', 'mode main']
# 	alt-shift-k = ['join-with up', 'mode main']
# 	alt-shift-l = ['join-with right', 'mode main']

# [[on-window-detected]]
# 	if.app-id = 'com.mitchellh.ghostty'
# 	run = "move-node-to-workspace 2"

# [[on-window-detected]]
# 	if.app-id = 'com.google.Chrome'
# 	run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace 1"
